//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brindar.Logica.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public Eventos()
        {
            this.EventoProveedores = new HashSet<EventoProveedores>();
        }
    
        public int IdEvento { get; set; }
        public int TipoEvento { get; set; }
        public int Organizador { get; set; }
        public Nullable<int> Salon { get; set; }
        public Nullable<int> Servicio { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Presupuesto { get; set; }
    
        public virtual ICollection<EventoProveedores> EventoProveedores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual TiposEvento TiposEvento { get; set; }
    }
}
