//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brindar.Logica.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincias
    {
        public Provincias()
        {
            this.Localidades = new HashSet<Localidades>();
        }
    
        public int IdProvincia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Localidades> Localidades { get; set; }
    }
}
