//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brindar.Logica.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salones
    {
        public int IdSalon { get; set; }
        public int Proveedor { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
        public string Telefono { get; set; }
        public int Provincia { get; set; }
        public int Localidad { get; set; }
        public string Direccion { get; set; }
        public string URLFacebook { get; set; }
        public string URLPagina { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
