//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brindar.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Brindar.Logica.Modelo;
    
    public partial class BrindarEntities : DbContext
    {
        public BrindarEntities()
            : base("name=BrindarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categorias> Categorias { get; set; }
        public DbSet<EventoProveedores> EventoProveedores { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<Localidades> Localidades { get; set; }
        public DbSet<Provincias> Provincias { get; set; }
        public DbSet<Salones> Salones { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<Suscripciones> Suscripciones { get; set; }
        public DbSet<TiposEvento> TiposEvento { get; set; }
        public DbSet<TiposUsuario> TiposUsuario { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
