//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brindar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizadores
    {
        public Organizadores()
        {
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int IdOrganizador { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }
    
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}
